# Data Handling in APIs - JSON

## Learning Objectives

After completing this notebook, you will be able to:

- Understand what JSON is
- Learn JSON syntax and structure
- Understand how APIs use JSON
- Convert Python objects to JSON
- Convert JSON to Python objects
- Work with nested JSON
- Extract information from API responses
- Flatten JSON for Data Analysis
- Handle missing values in JSON
- Normalize JSON using Pandas
- Work with real-world API response structures

---

## Why JSON Matters?

JSON is the most commonly used format for exchanging data between:

- Frontend and Backend
- Web Applications
- Mobile Applications
- APIs
- Databases
- Cloud Services
- Data Analytics Pipelines

Almost every API you encounter as a Data Analyst, Data Scientist, or Data Engineer will return data in JSON format.
___

___
# What is JSON?

JSON stands for:

**JavaScript Object Notation**

It is a lightweight text-based format used for storing and exchanging data.

Although it originated from JavaScript, JSON is language-independent and supported by almost every programming language.

---

## Real Life Analogy

Imagine filling a form:

Name: Himanshu <br>
Age: 26 <br>
City: Delhi <br>

JSON stores this information as:

```
{
    "name": "Himanshu",
    "age": 26,
    "city": "Delhi"
}
```

Each piece of information is stored as:

Key : Value

This is called a Key-Value Pair.
___

___
# JSON Syntax Rules

JSON follows some important rules:

1. Data is stored as Key-Value pairs.
2. Keys must be enclosed in double quotes.
3. Strings must use double quotes.
4. Objects are enclosed using { }.
5. Arrays are enclosed using [ ].
6. Data is separated using commas.
7. JSON supports nested structures.

---

## Valid Data Types in JSON

1. String
2. Number
3. Boolean
4. Array
5. Object
6. Null
___

In [1]:
sample_json = {
    "name": "Himanshu",
    "age": 26,
    "is_employed": True,
    "skills": ["Python", "SQL", "Power BI"],
    "salary": None
}

sample_json

{'name': 'Himanshu',
 'age': 26,
 'is_employed': True,
 'skills': ['Python', 'SQL', 'Power BI'],
 'salary': None}

# JSON Data Types

Let's understand each JSON data type.

In [2]:
json_data = {
    "string": "Python",
    "number": 100,
    "float": 99.5,
    "boolean": True,
    "array": [1, 2, 3],
    "object": {"city": "Delhi"},
    "null_value": None
}

json_data

{'string': 'Python',
 'number': 100,
 'float': 99.5,
 'boolean': True,
 'array': [1, 2, 3],
 'object': {'city': 'Delhi'},
 'null_value': None}

# JSON Object

A JSON Object is similar to a Python Dictionary.

Syntax:

{
    "key": value
}

---
# JSON Array

A JSON Array is similar to a Python List.

Syntax:

[
    value1,
    value2,
    value3
]

In [3]:
skills = [
    "Python",
    "SQL",
    "Power BI",
    "Machine Learning"
]

skills

['Python', 'SQL', 'Power BI', 'Machine Learning']

---
# Nested JSON

Most API responses contain nested JSON.

Nested means:

- Object inside object
- Array inside object
- Object inside array

This structure is extremely common in APIs.

In [4]:
employee = {
    "id": 101,
    "name": "Himanshu",
    "address": {
        "city": "Delhi",
        "country": "India"
    },
    "skills": [
        "Python",
        "SQL",
        "Power BI"
    ]
}

employee

{'id': 101,
 'name': 'Himanshu',
 'address': {'city': 'Delhi', 'country': 'India'},
 'skills': ['Python', 'SQL', 'Power BI']}

In [6]:
print(employee["address"])
print(employee["address"]["city"])
print(employee["skills"][0])

{'city': 'Delhi', 'country': 'India'}
Delhi
Python

---
# Python Dictionary vs JSON

| Python Dictionary | JSON |
|------------|---------|
| Single Quotes Allowed | Double Quotes Required |
| True | true |
| False | false |
| None | null |
| dict | object |
| list | array |

Remember:

JSON and Python Dictionary look similar but are not exactly the same.

---
# JSON Module in Python

Python provides a built-in module called:

json

This module helps us:

1. Convert Python → JSON
2. Convert JSON → Python

# Convert Python Dictionary to JSON

Method:

json.dumps()

dumps = dump string

In [7]:
import json

employee = {
    "name": "Himanshu",
    "age": 26
}

json_string = json.dumps(employee)

print(json_string)
print(type(json_string))

{"name": "Himanshu", "age": 26}
<class 'str'>

| Function       | Purpose              | Input         | Output         |
| -------------- | -------------------- | ------------- | -------------- |
| `json.dump()`  | Python → JSON File   | Python Object | Writes to file |
| `json.dumps()` | Python → JSON String | Python Object | JSON String    |
| `json.load()`  | JSON File → Python   | JSON File     | Python Object  |
| `json.loads()` | JSON String → Python | JSON String   | Python Object  |

In [35]:
import json

employee = {
    "name": "Himanshu",
    "age": 26
}

json_string = json.dumps(employee)

print(json_string)
print(type(json_string))

{"name": "Himanshu", "age": 26}
<class 'str'>

In [36]:
import json

json_string = '''
{
    "name":"Himanshu",
    "age":26
}
'''

python_dict = json.loads(json_string)

print(python_dict)
print(type(python_dict))

{'name': 'Himanshu', 'age': 26}
<class 'dict'>

In [40]:
import json

employee = {
    "name": "Himanshu",
    "age": 26
}

with open("employee.json", "w") as file:
    json.dump(employee, file, indent=4)

print(employee)
print(type(file))

{'name': 'Himanshu', 'age': 26}
<class '_io.TextIOWrapper'>

In [38]:
import json

with open("employee.json", "r") as file:
    data = json.load(file)

print(data)
print(type(data))

{'name': 'Himanshu', 'age': 26}
<class 'dict'>

---
# Pretty Printing JSON

For readability we use:

indent parameter

In [8]:
pretty_json = json.dumps(employee, indent=4)

print(pretty_json)

{
    "name": "Himanshu",
    "age": 26
}

---
# Convert JSON String to Python Dictionary

Method:

json.loads()

loads = load string

In [12]:
json_string = '''
{
    "name":"Himanshu",
    "age":26
}
'''

python_dict = json.loads(json_string)

print(type(json_string))
print(python_dict)
print(type(python_dict))

<class 'str'>
{'name': 'Himanshu', 'age': 26}
<class 'dict'>

# JSON Files

Many APIs save responses into .json files.

Example:

employee.json

We can read and write JSON files easily.

In [14]:
employee = {
    "name": "Himanshu",
    "age": 26,
    "city": "Delhi"
}

with open("employee.json", "w") as file:
    json.dump(employee, file, indent=4)

print("File Saved")

with open("employee.json", "r") as file:
    data = json.load(file)

print(data)

File Saved
{'name': 'Himanshu', 'age': 26, 'city': 'Delhi'}

# JSON and APIs

Almost every API sends data in JSON format.

Typical API Flow:

Client-->API Request-->Server-->JSON Response-->Python-->Analysis

### Example API Response

This is how a typical API response looks:

In [16]:
api_response = {
    "status": "success",
    "data": {
        "id": 101,
        "name": "Himanshu",
        "city": "Delhi"
    }
}

print(api_response)
print(api_response["status"])

{'status': 'success', 'data': {'id': 101, 'name': 'Himanshu', 'city': 'Delhi'}}
success

## Real API Example using Requests

requests library is used to interact with APIs.

In [18]:
!pip install requests

Collecting requests
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.7-cp311-cp311-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.4.7-cp311-cp311-win_amd64.whl (159 kB)
Downloading idna-3.18-py3-none-any.whl (65 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading certifi-2026.5.20-py3-none-any.whl (134 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests

   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   -------- ------------------------------- 1/5 [idna]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ------------------------ --------------- 3/5 [certifi]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]

Successfully installed certifi-2026.5.20 charset_normalizer-3.4.7 idna-3.18 requests-2.34.2 urllib3-2.7.0

In [19]:
import requests

url = "https://jsonplaceholder.typicode.com/users"

response = requests.get(url)

response.status_code

200

In [25]:
data = response.json()

print(type(data))
print(data)
print()
print(data[0]["email"])

<class 'list'>
[{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}, {'id': 2, 'name': 'Ervin Howell', 'username': 'Antonette', 'email': 'Shanna@melissa.tv', 'address': {'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}, 'phone': '010-692-6593 x09125', 'website': 'anastasia.net', 'company': {'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'}}, {'id': 3, 'name': 'Clementine Bauch', 'username': 'Samantha', 'email': 'Nathan@yesenia.net', 'address': {'street': 'Douglas Extension', 'suite': 'Suite 847', 'city': 'McKenziehaven', 'zipcode': '59590-4157', 'geo': {'lat': '-68.6102', 'lng': '-47.0653'}}, 'phone': '1-463-123-4447', 'website': 'ramiro.info', 'company': {'name': 'Romaguera-Jacobson', 'catchPhrase': 'Face to face bifurcated interface', 'bs': 'e-enable strategic applications'}}, {'id': 4, 'name': 'Patricia Lebsack', 'username': 'Karianne', 'email': 'Julianne.OConner@kory.org', 'address': {'street': 'Hoeger Mall', 'suite': 'Apt. 692', 'city': 'South Elvis', 'zipcode': '53919-4257', 'geo': {'lat': '29.4572', 'lng': '-164.2990'}}, 'phone': '493-170-9623 x156', 'website': 'kale.biz', 'company': {'name': 'Robel-Corkery', 'catchPhrase': 'Multi-tiered zero tolerance productivity', 'bs': 'transition cutting-edge web services'}}, {'id': 5, 'name': 'Chelsey Dietrich', 'username': 'Kamren', 'email': 'Lucio_Hettinger@annie.ca', 'address': {'street': 'Skiles Walks', 'suite': 'Suite 351', 'city': 'Roscoeview', 'zipcode': '33263', 'geo': {'lat': '-31.8129', 'lng': '62.5342'}}, 'phone': '(254)954-1289', 'website': 'demarco.info', 'company': {'name': 'Keebler LLC', 'catchPhrase': 'User-centric fault-tolerant solution', 'bs': 'revolutionize end-to-end systems'}}, {'id': 6, 'name': 'Mrs. Dennis Schulist', 'username': 'Leopoldo_Corkery', 'email': 'Karley_Dach@jasper.info', 'address': {'street': 'Norberto Crossing', 'suite': 'Apt. 950', 'city': 'South Christy', 'zipcode': '23505-1337', 'geo': {'lat': '-71.4197', 'lng': '71.7478'}}, 'phone': '1-477-935-8478 x6430', 'website': 'ola.org', 'company': {'name': 'Considine-Lockman', 'catchPhrase': 'Synchronised bottom-line interface', 'bs': 'e-enable innovative applications'}}, {'id': 7, 'name': 'Kurtis Weissnat', 'username': 'Elwyn.Skiles', 'email': 'Telly.Hoeger@billy.biz', 'address': {'street': 'Rex Trail', 'suite': 'Suite 280', 'city': 'Howemouth', 'zipcode': '58804-1099', 'geo': {'lat': '24.8918', 'lng': '21.8984'}}, 'phone': '210.067.6132', 'website': 'elvis.io', 'company': {'name': 'Johns Group', 'catchPhrase': 'Configurable multimedia task-force', 'bs': 'generate enterprise e-tailers'}}, {'id': 8, 'name': 'Nicholas Runolfsdottir V', 'username': 'Maxime_Nienow', 'email': 'Sherwood@rosamond.me', 'address': {'street': 'Ellsworth Summit', 'suite': 'Suite 729', 'city': 'Aliyaview', 'zipcode': '45169', 'geo': {'lat': '-14.3990', 'lng': '-120.7677'}}, 'phone': '586.493.6943 x140', 'website': 'jacynthe.com', 'company': {'name': 'Abernathy Group', 'catchPhrase': 'Implemented secondary concept', 'bs': 'e-enable extensible e-tailers'}}, {'id': 9, 'name': 'Glenna Reichert', 'username': 'Delphine', 'email': 'Chaim_McDermott@dana.io', 'address': {'street': 'Dayna Park', 'suite': 'Suite 449', 'city': 'Bartholomebury', 'zipcode': '76495-3109', 'geo': {'lat': '24.6463', 'lng': '-168.8889'}}, 'phone': '(775)976-6794 x41206', 'website': 'conrad.com', 'company': {'name': 'Yost and Sons', 'catchPhrase': 'Switchable contextually-based project', 'bs': 'aggregate real-time technologies'}}, {'id': 10, 'name': 'Clementina DuBuque', 'username': 'Moriah.Stanton', 'email': 'Rey.Padberg@karina.biz', 'address': {'street': 'Kattie Turnpike', 'suite': 'Suite 198', 'city': 'Lebsackbury', 'zipcode': '31428-2261', 'geo': {'lat': '-38.2386', 'lng': '57.2232'}}, 'phone': '024-648-3804', 'website': 'ambrose.net', 'company': {'name': 'Hoeger LLC', 'catchPhrase': 'Centralized empowering task-force', 'bs': 'target end-to-end models'}}]

Sincere@april.biz

# Convert API JSON into DataFrame

This is one of the most common Data Analyst tasks.

In [26]:
import pandas as pd

df = pd.DataFrame(data)

df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

# Understanding Complex Nested API Responses

Real APIs are rarely flat.

Most responses contain nested structures.

In [27]:
nested_data = {
    "user": {
        "id": 101,
        "name": "Himanshu",
        "address": {
            "city": "Delhi",
            "country": "India"
        }
    }
}

nested_data["user"]["address"]["city"]

'Delhi'

# Flattening Nested JSON

Data Analysts often need flat tables.

Pandas provides:

json_normalize()

In [28]:
from pandas import json_normalize

flat_df = json_normalize(nested_data)

flat_df

   user.id user.name user.address.city user.address.country
0      101  Himanshu             Delhi                India

# Working with Arrays in JSON

In [31]:
employee = {
    "name": "Himanshu",
    "skills": [
        "Python",
        "SQL",
        "Power BI"
    ]
}

print(employee["skills"])
for skill in employee["skills"]:
    print(skill)

['Python', 'SQL', 'Power BI']
Python
SQL
Power BI

# Handling Missing Keys

Not every API response contains every key.

Using get() prevents errors.

In [33]:
employee = {
    "name": "Himanshu"
}

# employee["salary"] #this will raise a KeyError since the key "salary" is not present in the dictionary

employee.get("salary")  # returns None if key is not present in dictionary

employee.get("salary", "Salary information not available")  #2nd argument is default value if key is not present in dictionary

'Salary information not available'

# Common API Status Codes

| Code | Meaning |
|--------|---------|
| 200 | Success |
| 201 | Created |
| 400 | Bad Request |
| 401 | Unauthorized |
| 403 | Forbidden |
| 404 | Not Found |
| 500 | Internal Server Error |

Always check status codes before processing JSON.

In [34]:
response = requests.get("https://jsonplaceholder.typicode.com/users")

if response.status_code == 200:
    print("Success")
else:
    print("Failed")

Success

# Interview Questions

1. What is JSON?
2. Difference between JSON and Dictionary?
3. What is json.dumps()?
4. What is json.loads()?
5. What is nested JSON?
6. How do APIs use JSON?
7. What is json_normalize()?
8. How do you handle missing keys?
9. Difference between dump and dumps?
10. Difference between load and loads?

# Summary

JSON is the backbone of modern APIs.

Important Topics Covered:

✓ JSON Basics

✓ JSON Syntax

✓ JSON Data Types

✓ Nested JSON

✓ JSON Objects

✓ JSON Arrays

✓ JSON Module

✓ dumps()

✓ loads()

✓ dump()

✓ load()

✓ API Responses

✓ requests Library

✓ DataFrame Conversion

✓ json_normalize()

✓ Missing Values

✓ Status Codes

These concepts are mandatory for:
- Data Analyst
- Data Scientist
- Data Engineer
- Machine Learning Engineer
- Backend Developer
- API Developer